<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Madstack
 * @version     0.1.0
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 * 
 */
?>
<?php 

if(Mage::getStoreConfig('madstack/madstack/installation_config') != 2 ){
	$result = Mage::helper('madstack')->curlFunc(array('domain'=>Mage::getBaseURL(),'install_id'=>Mage::helper('madstack')->generateUUID()),'https://contus.madstreetden.com/install/');
	if($result['success'] == true){
		Mage::getModel('core/config')->saveConfig('madstack/madstack/installation_config', 2);	
	}
}


?>
<iframe src='https://contus.madstreetden.com/?domain=<?php echo Mage::getBaseURL();?>' name="frame1" scrolling="auto" frameborder="no" align="center" height = "700px" width = "100%"></iframe>

