<?php
/**
* Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Madstack
* @version     0.1.0
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2015 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
* 
*/
?>
<?php 
/*
 * Track event for after complete the order success page
*/
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderId);

$orderItems = $order->getAllItems();

foreach($orderItems as $item) {
	$productID 		= $productID.$item->getProductId().'_';
	$categoryName	= $categoryName.Mage::helper('madstack')->getCategoryName($item->getProductId()).'_';
	$productPrice	= $productPrice.round($item->getPrice(),2).'_';
	$productQuanity = $productQuanity.round($item->getQtyOrdered(),0).'_';
}

$trackinArray				= Mage::helper('madstack')->buildTrackArray('buy',rtrim($productID,'_'),rtrim($categoryName,'_'));
$trackinArray['prodPrice']	= rtrim($productPrice,'_');
$trackinArray['prodQty']	= rtrim($productQuanity,'_');

echo Mage::helper('madstack')->trackEvent($trackinArray);



?>